// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoVPtm3exZ4OMaHEw9ADt2g_-i3D93zdQ',
    appId: '1:165440244528:android:403e019f812c0860a016f5',
    messagingSenderId: '165440244528',
    projectId: 'lab10-cc3f3',
    storageBucket: 'lab10-cc3f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_pSFMLZsp097j3DaXzJX2sxlxuBKnqPw',
    appId: '1:165440244528:ios:310c2fe995d084e8a016f5',
    messagingSenderId: '165440244528',
    projectId: 'lab10-cc3f3',
    storageBucket: 'lab10-cc3f3.appspot.com',
    androidClientId: '165440244528-inqbeehoud7n6okl1c0ar2bup1g85ue1.apps.googleusercontent.com',
    iosClientId: '165440244528-nds9i5d5lnt33tipvqft36em64b6m0l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab10',
  );
}
